import React from 'react'
import './Loading.css'

function Loading() {
    return (
        <div class='spinner'>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
        </div>
    )
}

export default Loading
